name: BA
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aiohappyeyeballs=2.4.4=py313h06a4308_0
  - aiohttp=3.11.10=py313h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - attrs=24.3.0=py313h06a4308_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313hf0014fa_0
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.15=h06a4308_0
  - captum=0.7.0=py313h06a4308_0
  - certifi=2025.8.3=py313h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py313h06a4308_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cuda-cccl_linux-64=12.4.127=h06a4308_2
  - cuda-crt-dev_linux-64=12.4.131=h06a4308_0
  - cuda-crt-tools=12.4.131=h06a4308_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart-dev=12.4.127=h99ab3db_0
  - cuda-cudart-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart-static=12.4.127=h99ab3db_0
  - cuda-cudart-static_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cuobjdump=12.4.127=h6a678d5_1
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-driver-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-nvcc=12.4.131=h02f8991_0
  - cuda-nvcc-dev_linux-64=12.4.131=h4ee8466_0
  - cuda-nvcc-impl=12.4.131=h99ab3db_0
  - cuda-nvcc-tools=12.4.131=h99ab3db_0
  - cuda-nvcc_linux-64=12.4.131=he92618c_0
  - cuda-nvdisasm=12.4.127=h6a678d5_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-nvvm-dev_linux-64=12.4.131=h06a4308_0
  - cuda-nvvm-impl=12.4.131=h6a678d5_0
  - cuda-nvvm-tools=12.4.131=h6a678d5_0
  - cuda-version=12.4=hbda6634_3
  - cudnn=9.1.1.17=cuda12_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - deprecated=1.2.13=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - filelock=3.17.0=py313h06a4308_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py313h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py313h5eee18b_0
  - fsspec=2025.3.2=py313h7040dfc_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py313h5eee18b_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - importlib-metadata=8.5.0=py313h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py313h06a4308_0
  - joblib=1.4.2=py313h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libllvm19=19.1.7=he89c38a_1
  - libmlir19=19.1.7=hdb19cb5_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnvjitlink=12.4.127=h99ab3db_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=hdbd6064_0
  - libprotobuf=5.29.3=hc99497a_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.5.1=gpu_cuda124_hf726350_304
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - lightning=2.5.0.post0=py313h06a4308_0
  - lightning-utilities=0.11.9=py313h06a4308_0
  - lit=17.0.6=py313h06a4308_1
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.7.1=ha545f22_0
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.0=py313h06a4308_1
  - matplotlib-base=3.10.0=py313h68cf311_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py313h06a4308_0
  - multidict=6.1.0=py313h5eee18b_0
  - mysql=8.4.0=h721767e_2
  - nccl=2.21.5.1=ha515578_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.4.2=py313h06a4308_0
  - numexpr=2.10.1=py313h3c60e43_0
  - numpy=2.2.5=py313h8d96ed3_0
  - numpy-base=2.2.5=py313h8e760e0_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.17=h5eee18b_0
  - opentelemetry-api=1.30.0=py313h06a4308_0
  - packaging=24.2=py313h06a4308_0
  - pandas=2.2.3=py313h6a678d5_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py313hac6e08b_1
  - pip=25.1=pyhc872135_2
  - propcache=0.3.1=py313h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=6.7.1=py313h6a678d5_1
  - pyqt6-sip=13.9.1=py313h5eee18b_1
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.2=hf623796_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytorch=2.5.1=gpu_cuda124_py313hfee4293_304
  - pytorch-lightning=2.5.0.post0=py313h06a4308_0
  - pytz=2024.1=py313h06a4308_0
  - pyyaml=6.0.2=py313h5eee18b_0
  - qtbase=6.7.3=hdaa5aa8_0
  - qtdeclarative=6.7.3=h6a678d5_0
  - qtsvg=6.7.3=he621ea3_0
  - qttools=6.7.3=h80c7b02_0
  - qtwebchannel=6.7.3=h6a678d5_0
  - qtwebsockets=6.7.3=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py313h06a4308_1
  - scikit-learn=1.6.1=py313h6a678d5_0
  - scipy=1.15.3=py313h7f54423_0
  - setuptools=72.1.0=py313h06a4308_0
  - sip=6.10.0=py313h6a678d5_0
  - six=1.17.0=py313h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py313h06a4308_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tabulate=0.9.0=py313h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py313h7040dfc_0
  - tk=8.6.14=h39e8969_0
  - torchmetrics=1.4.0.post0=py313h06a4308_0
  - tornado=6.5=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_0
  - triton=3.1.0=cuda124py313hac27663_3
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.3.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - wrapt=1.17.0=py313h5eee18b_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py313h5eee18b_0
  - zipp=3.21.0=py313h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - adjusttext==1.3.0
      - alembic==1.17.0
      - anyio==4.10.0
      - bokeh==3.7.3
      - bottle==0.13.4
      - build==1.3.0
      - cachecontrol==0.14.3
      - cffi==1.17.1
      - cleo==2.1.0
      - colorlog==6.9.0
      - crashtest==0.4.1
      - cryptography==45.0.7
      - curve-curator==0.6.0
      - distlib==0.4.0
      - drevalpy==1.3.6
      - dulwich==0.22.8
      - fastjsonschema==2.21.2
      - findpython==0.6.3
      - flaky==3.8.1
      - git-filter-repo==2.47.0
      - gprofiler-official==1.0.0
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - installer==0.7.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jeepney==0.9.0
      - keyring==25.6.0
      - mako==1.3.10
      - more-itertools==10.8.0
      - msgpack==1.1.1
      - narwhals==2.3.0
      - optuna==4.5.0
      - optuna-dashboard==0.19.0
      - optuna-integration==4.5.0
      - patsy==1.0.1
      - pbs-installer==2025.9.2
      - pkginfo==1.12.1.2
      - platformdirs==4.4.0
      - plotly==6.3.0
      - pluggy==1.6.0
      - poetry==2.1.4
      - poetry-core==2.1.3
      - psutil==7.0.0
      - pycparser==2.22
      - pyproject-hooks==1.2.0
      - pytest==7.4.4
      - rapidfuzz==3.14.0
      - requests-toolbelt==1.0.0
      - scikit-posthocs==0.11.4
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.44
      - statsmodels==0.14.5
      - toml==0.10.2
      - tomlkit==0.13.3
      - torch-geometric==2.6.1
      - trove-classifiers==2025.8.26.11
      - virtualenv==20.32.0
      - xyzservices==2025.4.0
      - zstandard==0.24.0
prefix: /storage/mi/zhaow01/miniconda3/envs/BA
